### ISSUE TITLE
For some reason the ai never upgrades the basic barracks units like militia, archers and spearmen.

### ISSUE THREAD

**Issue by pulkit24** [pulkit24/ToME#234]
It's on every map I've played. First time was Gondor but the next maps I played were random. The one I'm currently playing looks like Harad because there are mumak calfs (wich I can't hunt even though they seem to be a food source). I've played with Numenor, Mordor, and Lothlorien. It were all 8 player games. It seems to be regardless of wich map or faction I play. They do upgrade the other units like cavalry and javelineers and orcs, (although I'm not certain about the castle units) but they keep fighting the entire game with militia, archers and spearmen without upgrading them.

**Comment by UhrMensch** [comment]
Just a small comment to help you fix this (I am usually a silent observer/player of your and other great mods): The AI constants ri-man-of-arms and ri-marksman are set to the wrong values: it should be 
(defconst ri-man-of-arms 223)
instead of
(defconst ri-man-of-arms 222)
and
(defconst ri-marksman 105)
instead of
(defconst ri-marksman 100)

Also the constant ri-pikeman is not set at all since the command
(defconst ri-pikeman 197)
is commented out. It is in the file 60027 in gamedata_x1.drs. I found it while trying to fix it in a slightly older version.

**Comment by pulkit24** [comment]
Hey thanks! Saved me hours of investigation! Will fix ASAP this weekend.
